[package]
name = "dbuf"
version = "0.1.0"
edition = "2021"

[features]

default = ["std", "triomphe"]

std = ["alloc", "dep:slab"]
alloc = ["dep:rc-box"]
triomphe = ["dep:triomphe"]

[dependencies]

[dependencies.rc-box]
optional = true
version = "1"
default-features = false

[dependencies.triomphe]
optional = true
version = "0.1.11"
default-features = false

[dependencies.slab]
optional = true
version = "0.4"
default-features = false

[dev-dependencies.pollster]
vesrion = "0.3"
features = ["macro"]
